### ISSUE TITLE
No visible @ interface declares the selector "shuffledArray"

### ISSUE THREAD

**Issue by TeamRainless** [bryanluby/NSArray-Shuffle#1]
Your method, as it turns out, is NOT "shuffledArray" as you indicated in the readme and on the github page... but it's actually "bjl_shuffledArray":
# import "NSArray+Shuffle.h"

@implementation NSArray (Shuffle)
## \- (NSArray *)bjl_shuffledArray

So if one were to import your header and try:

myArray = [largerArray shuffledArray]

...which is how you would imagine this was supposed to work... you would get "No @ interface for NSArray declares the selector "shuffledArray".

bjl_shuffledArray will return the correct result.

**Comment by bryanluby** [comment]
:+1:  Thanks for spotting this. Pushing up a fix.
